### ISSUE TITLE
AI features?

### ISSUE THREAD

**Issue by tansir23** [jdolny/Prime-Ball-Controller-Docs#1]
Hello, 
I really like your Prime-Ball-Controller Unity Assets Store. Is it possible to add some AI features to it, such as tracking targets, accelerating towards targets, and setting waypoints for it to cruise freely, really need these features, looking forward to your reply, is there any other way to contact you? Thank you!

**Comment by jdolny** [comment]
I can look into adding some of these features.  I've never done any AI work so it will probably take some time.  Most people just email me directly.

**Comment by tansir23** [comment]
> I can look into adding some of these features. I've never done any AI work so it will probably take some time. Most people just email me directly.

I just want to confirm if you received the email I sent you last week. As for the AI features of this plugin, I would like to know approximately when it can be updated. I can wait for it. Thank you very much!
