### ISSUE TITLE
Convert Mana Prime Controller to Mobile Control

### ISSUE THREAD

**Issue by subikhan402** [jdolny/Prime-Ball-Controller-Docs#2]
Hi,

I have recently purchased a  Prime Ball controller, and I want to use it with my mobile device. However, I could not find any guidance or instructions in the documentation on how to achieve this.

Here are the steps I've tried so far:

Attempted to connect and configure it with my mobile device.
Used Control Freak (CF2), but it did not work either.
Despite these efforts, I haven't been able to get it to function correctly on my mobile.

Could you please guide me on how to convert the Prime Ball controller to be used with a mobile device? Any assistance or documentation would be greatly appreciated.

**Comment by jdolny** [comment]
I'll try and get mobile controls into the next release.

**Comment by jdolny** [comment]
This is now available in the 1.3.0 release.
