### ISSUE TITLE
Connecting Controller to Unity Netcode

### ISSUE THREAD

**Issue by PuR0kY** [jdolny/Prime-Ball-Controller-Docs#4]
Hi guys,
I was wondering if there is possibility of connecting your controller to be able to playing online. I am now trying to implenent Unity Netcode to you controller but not really getting any results that I would like...

Can you hint me with basic setup to be able to make controller work online? Every tip is appreciated!

**Comment by jdolny** [comment]
Hello, I don't have any experience with online play or Netcode so I probably can't help much right now.  I could try to get a project setup and see if I can figure it out though.  Is there is simple Netcode project that I could use as a template to see why it wouldn't work?  I guess I don't really understand why it wouldn't work online if it works locally?  I can try and check some tutorials for netcode to test but I'm fairly busy with the holidays coming up.  I'll try and get to it as soon as I can.

**Comment by PuR0kY** [comment]
I was following Unity documentation, it is very straight forward but  controller is very complex and I think it will require more digging through your scripts than tutorials could really show..

I made prefab Player with Network Objects, NetworkManager GameObject, and NetworkObject on Plane that I use as a Arena and there is an issue with syncing, because when there is one instance (Server + Client) its works alright but when new client joins, its stops really syncing, for example camera of first player starts focusing newly connected player etc. I think there has to be some way. I am still trying to figure it out. Just wanted to ask if you ever have tried it.. my idea is that it will need some tinkering around all the directors you implemented..

**Comment by jdolny** [comment]
I had a chance to look into this.  Here is how I got it working.
**Add this code to the SphereDirector script:**

public override void OnNetworkSpawn()
 {
                 if (!IsOwner)
            {
                DataManager.Cameras.PlayerCamera.gameObject.SetActive(false);
                DataManager.Cameras.FreeLookCamera.gameObject.SetActive(false);
                DataManager.Cameras.SideScrollCamera.gameObject.SetActive(false);
                DataManager.Cameras.MagnetCamera.gameObject.SetActive(false);
                DataManager.Cameras.ProjectileCamera.gameObject.SetActive(false);
                DataManager.Cameras.OverheadCamera.gameObject.SetActive(false);
                DataManager.Cameras.MagnetCeilingCamera.gameObject.SetActive(false);
                DataManager.Cameras.StationaryCamera.gameObject.SetActive(false);
                DataManager.Cameras.FirstPersonCamera.gameObject.SetActive(false);
            }
            enabled = IsOwner;
}

remember to change the monobehaviour to networkbehavior

**Then on the Player prefab:**

- Add a network object to the top level Player component
- Add a Network Transform to the rigidbody component of the player and only sync the position of x ,y, and z
- Add another Network Transform to the Outermesh component of the player and only sync the position and rotation for x, y and z

I'll try to add some more information to the documentation sometime this week.

**Comment by PuR0kY** [comment]
That is looking promising! 
I was just digging inside your logic and was thinking it has something to do with that DataManager!

I'm looking forward to it. Working multiplayer logic could definitely add some value to it!!

Thank you so much! Lmk when documentation or some other features will be in place :)

**Comment by jdolny** [comment]
Documentation is now available.
http://primeballcontroller.com/netcode/gameobjects/

**Comment by PuR0kY** [comment]
Works like a charm! Very usefull documentation! I will continue with new ideas if I find some while developing. You really helped me. Thanks man! 

We can close this issue

**Comment by jdolny** [comment]
No problem, glad to help.  Have a great one.
